### ISSUE TITLE
ConceptRef evaluator not implemented

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#421] opened 2020-10-21 21:41 UTC
The following library:

```
library TestConceptRef

using FHIR version '4.0.1'

codesystem "LOINC": 'http://loinc.org'

code "Pregnancy status code": '82810-3' from "LOINC" display 'Pregnancy status'

concept "Pregnancy status": { "Pregnancy status code" } display 'Pregnancy status'

context Patient

define PregnancyStatus: "Pregnancy status"
```

Results in "ConceptRef evaluate not implemented" when executed in the engine.

**Comment by dkwasny-ibm** [comment] 2020-11-06 23:05
I'm giving this issue a go, but if possible, I'd like a rough yes/no on whether my approach makes sense.  I'm still pretty new to this codebase 😄 

From what I can tell, the issue is rooted in the fact that there are no `Evaulator` classes for `ConceptRef` and `ConceptDef`.
All I think I need to do is create said classes, and hook them into `ObjectFactoryEx`.
I have my preliminary changes [in a fork](https://github.com/DBCG/cql_engine/compare/develop...dkwasny-ibm:421-concept-ref-evaluator), but I still need to finish writing tests.
I pretty much modeled everything after the corresponding classes for the `Code` type.

Also, I think the example CQL is slightly off since the define references the code rather than the concept.

**Comment by brynrhodes** [comment] 2020-11-06 23:09
Yes, that's exactly the right implementation.
And yes, the example isn't quite right, I'll fix that.

**Comment by brynrhodes** [comment] 2020-11-06 23:12
I actually removed the retrieve reference, since it's not strictly necessary for this repro

**Comment by dkwasny-ibm** [comment] 2020-11-06 23:14
Thank you for the quick response!
I'll try to get a PR spun up early next week.

**Comment by JPercival** [comment] 2020-11-20 21:40
Resolved by #432

**Closed by JPercival** 2020-11-20 21:40 UTC
Labels: bug
