### ISSUE TITLE
Quality comparison ignores unit

### ISSUE THREAD

**Issue by barhodes** [DBCG/cql_engine#391] opened 2020-08-05 20:21 UTC
The following logic will always return the Observation regardless of what the unit is set to in the resource.

["Observation": "PSA Lab Test Exclusion"] AbnormalPSAResult
    where AbnormalPSAResult.value > 4.0 'ng/mL'

**Comment by barhodes** [comment] 2020-08-05 20:23
Sample observation:
{
        "resourceType": "Observation",
        "id": "psa-001-psatest1",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-08-05T13:50:04.601+00:00",
          "source": "#8VIkzZ7CLtTreyqM"
        },
        "status": "final",
        "code": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "443174008",
              "display": "Measurement of prostate specific antigen using ultrasensitive assay"
            }
          ]
        },
        "subject": {
          "reference": "Patient/psa-001"
        },
        "effectiveDateTime": "2011-12-31T23:59:00Z",
        "valueQuantity": {
        	"value": "5",
        	"unit": "pq/dL"
        }
}

**Comment by JPercival** [comment] 2021-04-22 16:08
Duplicate of #167, #43, #306

**Closed by JPercival** 2021-04-22 16:08 UTC
